name: microproject-01-trends-in-high-school-gpas Grading
'on':
  workflow_dispatch: {}
permissions:
  actions: write
  contents: read
  checks: read
jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      id: sr-checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
        cache-dependency-path: microproject-01-trends-in-high-school-gpas/requirements.txt
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v4
      with:
        repository: dsdiscovery/microprojects
        ref: microproject-01-trends-in-high-school-gpas
        path: release
    - name: Checkout cell replacer
      id: cell-replace-checkout
      uses: actions/checkout@v4
      with:
        repository: dsdiscovery/cell-replace
        path: cell-replace
    - name: Copy up-to-date grading files from release
      id: local-copy
      uses: illinois/local-copy@v2
      with:
        src_path: release/microproject-01-trends-in-high-school-gpas
        dst_path: microproject-01-trends-in-high-school-gpas
        copy: '.github/classroom : .github/classroom, requirements.txt : requirements.txt'
    - run: pip install -r microproject-01-trends-in-high-school-gpas/requirements.txt
    - name: Run cell-replace
      run: python cell-replace/cell-replace.py microproject-01-trends-in-high-school-gpas/microproject-01-trends-in-high-school-gpas.ipynb release/microproject-01-trends-in-high-school-gpas/microproject-01-trends-in-high-school-gpas.ipynb
    - name: Generate Test Script
      run: 'python3 -m jupyter2pytest microproject-01-trends-in-high-school-gpas/microproject-01-trends-in-high-school-gpas.ipynb "### TEST CASE for (.*)" microproject-01-trends-in-high-school-gpas/test_microproject-01-trends-in-high-school-gpas.py '
    - name: Generate Grading Artifacts
      run: cd microproject-01-trends-in-high-school-gpas && python3 test_microproject-01-trends-in-high-school-gpas.py && cd ..
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v6
      with:
        path: microproject-01-trends-in-high-school-gpas/
        test_suite: autograding
        step_summary: true
